baseURL = ""
title = "EV Advisory"

languageCode = "en-us"
DefaultContentLanguage = "en"
googleAnalytics = 'G-M5ND57KYXW'
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 6
darkmode_js = ["assets/js/darkmode.js"]
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = true
copyright = "2023 EV Advisory - All rights reserved"
timeout = 120000

[Author]
    name = "EV Advisory"
    email = "info@evadvisory.ca"

[params]
homeURL = "https://evadvisory.ca"
taxonomies = "tags"
author = "EV Advisory"
authorimage = "../assets/images/global/author.webp"
github = "EV-Advisory"
facebook = "https://facebook.com/evadvisory"
og_image = "/images/tailbliss-cover.png"
sitename = "EV Advisory"
twitter = "evadvisoryltd"
instagram = "evadvisory"
dribbble = "evadvisory"
gtm_id = "GTM-TWK47J8"
fb_id = "588541705981208"
CADPhone = "647-542-9921"
USAPhone = "786-529-6998"
description = "Intersecting AI and BI to evolve your business"
mainSections = ['services']
hero_title = "EV Advisory"
hero_subtitle = "Optimize. Scale. Automate."
hero_CTA = "Let's talk about your website"
hero_CTA_link = "/services/data-strategy"
hero_img= "assets/images/global/intro-hero-cdc.jpg"
hero_lead_CTA = "Customer-first data strategy"  
hero_description = "Join the data revolution with EV Advisory! Our mission is to empower your business to unleash its full potential and dominate the game with analytics that pack a powerful punch. Get ready to be the envy of the industry and experience the data-driven success your business deserves."    
mission_quote = "Stay ahead in the digital age with our expert insights and top-tier talent. Learn how to navigate the ever-changing technological landscape and stay competitive in today's rapidly evolving business world."    


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = ["Categories"]
tag = ["Tags"]

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'services'
  weight = 100
[[related.indices]]
  name = 'insights'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
[params.csp]
  childsrc = ["'self'"]
  fontsrc = ["'self'",
    "https://use.fontawesome.com",
    "https://fonts.gstatic.com",
    "https://public.slidesharecdn.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  formaction = ["'self'",
    "https://syndication.twitter.com/",
    "https://platform.twitter.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  framesrc = ["'self'",
    "https://cse.google.com",
    "https://player.vimeo.com",
    "www.youtube.com",
    "www.youtube-nocookie.com",
    "https://platform.twitter.com",
    "https://syndication.twitter.com",
    "https://jsfiddle.net",
    "fiddle.jshell.net",
    "*.jsfiddle.net",
    "www.instagram.com",
    "https://kuula.co",
    "https://www.slideshare.net",
    "https://www.google.com",
    "https://googleads.g.doubleclick.net",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  imgsrc = ["'self'",
    "https://jeremylikness.visualstudio.com",
    "https://www.google-analytics.com",
    "https://stats.g.doubleclick.net",
    "https://pagead2.googlesyndication.com",
    "*.google.com",
    "*.gstatic.com",
    "*.amazon-adsystem.com",
    "https://www.googleapis.com",
    "https://images-na.ssl-images-amazon.com",
    "https://platform.twitter.com",
    "*.twimg.com",
    "https://syndication.twitter.com",
    "*.cdninstagram.com",
    "data:",
    "https://files.kuula.io",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  objectsrc = ["'none'"]
  stylesrc = ["'self'",
    "'unsafe-inline'",
    "https://use.fontawesome.com",
    "https://fonts.googleapis.com",
    "https://www.google.com",
    "https://platform.twitter.com",
    "*.twimg.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  scriptsrc = ["'self'",
    "'unsafe-inline'",
    "https://platform.twitter.com",
    "https://cdn.syndication.twimg.com",
    "*.amazon-adsystem.com",
    "https://www.google-analytics.com",
    "cse.google.com",
    "https://www.google.com",
    "https://pagead2.googlesyndication.com",
    "https://adservice.google.com",
    "*.googleadservices.com",
    "https://www.googletagservices.com",
    "*.googletagmanager.com",
    "jsfiddle.net",
    "www.instagram.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  prefetchsrc = ["'self'",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = false
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
    max = "0.110.0"
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = 'assets'
  target = 'static/assets'
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'data'
  target = 'data'

outputs = ["RSS"]
permalink = "index.xml"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.es]
    languageName = "Español"
    weight = 2
