baseURL = ""
title = "EV Advisory"

languageCode = "en-us"
DefaultContentLanguage = "en"
googleAnalytics = 'G-M5ND57KYXW'
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = true


[params]
author = "EV Advisory"
authorimage = "../assets/images/global/author.webp"
github = "https://github.com/EV-Advisory"
facebook = "https://facebook.com/evadvisory"
og_image = "/images/tailbliss-cover.png"
sitename = "EV Advisory"
twitter = "@evadvisoryltd"
gtm_id = "GTM-TWK47J8"
description = "Intersecting AI and BI"
mainSections = ['services']
hero_title = "EV Advisory"  
hero_subtitle = "Optimize. Scale. Automate."  
hero_CTA = "Let's connect"  
hero_img= "assets/images/global/intro-hero-cdc.jpg"     
hero_lead_CTA = "Data strategy that's right for you"
hero_description = "At EV Advisory, our primary objective is to enable your analytics capabilities to punch well above your weight. Data strategy, web and marketing capabilities that your business deserves"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Services"
tag = ["Tags"]

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'services'
  weight = 100
[[related.indices]]
  name = 'insights'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = false
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
    max = "0.105.0"
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = 'assets'
  target = 'static/assets'
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'data'
  target = 'data'
