baseURL = ""
title = "EV Advisory"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = true

[params]
author = "EV Advisory"
authorimage = "../assets/images/global/author.webp"
github = "https://github.com/EV-Advisory"
facebook = "https://facebook.com/evadvisory"
og_image = "/images/tailbliss-cover.png"
sitename = "EV Advisory"
twitter = "@evadvisoryltd"
description = "Intersecting AI and BI"
mainSections = ['services']
hero_title = "EV Advisory"  
hero_subtitle = "Optimize. Scale. Automate."  
hero_CTA = "Let's connect"  
hero_lead_CTA = "Data strategy that's right for you"
hero_description = "At EV Advisory, our primary objective is to enable your analytics capabilities to punch well above your weight. Data strategy, web and marketing capabilities that your business deserves"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Services"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
    max = "0.105.0"
