[build]
publish = "public"
command = "cd themes/tailbliss && git submodule update -f --init && cd ../.. && npm run build"

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "cd themes/tailbliss && git submodule update -f --init && cd ../.. && npm run build"

[context.split1.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd themes/tailbliss && git submodule update -f --init && cd ../.. && npm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.110.0"

[context.branch-deploy]
command = "cd themes/tailbliss && git submodule update -f --init && cd ../.. && npm run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.110.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
